/**
 * 资源清单 —— **由 tools/art/ludo/gen_manifest.mjs 生成,不要手改。**
 * 加了素材就重跑一遍脚本。加载页按这份清单预热缓存(DESIGN §2 ①)。
 */

/** 图片:用 Image() 预解码,进内存也进 HTTP 缓存 */
export const LUDO_IMAGES: string[] = [
  "/ludo/avatars/bot-square-v2.png",
  "/ludo/avatars/player-01-square-v2.png",
  "/ludo/avatars/player-02-square-v2.png",
  "/ludo/avatars/player-03-square-v2.png",
  "/ludo/avatars/player-04-square-v2.png",
  "/ludo/avatars/player-05-square-v2.png",
  "/ludo/avatars/player-06-square-v2.png",
  "/ludo/backgrounds/lobby-sky.png",
  "/ludo/board/board-gameplay-v2.png",
  "/ludo/board/board.png",
  "/ludo/effekseer/vs/Parts/Aura.png",
  "/ludo/effekseer/vs/Parts/Aura_2.png",
  "/ludo/effekseer/vs/Parts/ColorNoise.png",
  "/ludo/effekseer/vs/Parts/Gradient_2.png",
  "/ludo/effekseer/vs/Parts/Gradient__1.png",
  "/ludo/effekseer/vs/Parts/Gradient__3.png",
  "/ludo/effekseer/vs/Parts/Noise1.png",
  "/ludo/effekseer/vs/Parts/Noise2.png",
  "/ludo/effekseer/vs/Parts/Noise3.png",
  "/ludo/effekseer/vs/Parts/Noise4.png",
  "/ludo/effekseer/vs/Parts/Null.png",
  "/ludo/effekseer/vs/Parts/Particle1.png",
  "/ludo/effekseer/vs/Parts/Particle2.png",
  "/ludo/effekseer/vs/Parts/ParticleCore.png",
  "/ludo/effekseer/vs/Parts/Ring.png",
  "/ludo/effekseer/vs/Parts/Ring2.png",
  "/ludo/ui/button-cyan.png",
  "/ludo/ui/button-disabled.png",
  "/ludo/ui/button-green.png",
  "/ludo/ui/button-purple.png",
  "/ludo/ui/button-yellow.png",
  "/ludo/ui/dialog-panel.png",
  "/ludo/ui/game-logo.png",
  "/ludo/ui/game-start-dynamic.png",
  "/ludo/ui/game-start-table-dynamic-v1.png",
  "/ludo/ui/game-start.jpg",
  "/ludo/ui/gameplay-logo-v1.png",
  "/ludo/ui/icons/add-seat.png",
  "/ludo/ui/icons/chat-gameplay-v1.png",
  "/ludo/ui/icons/clock.png",
  "/ludo/ui/icons/close.png",
  "/ludo/ui/icons/coin-gameplay-v1.png",
  "/ludo/ui/icons/copy.png",
  "/ludo/ui/icons/create.png",
  "/ludo/ui/icons/crown.png",
  "/ludo/ui/icons/join.png",
  "/ludo/ui/icons/mute-gameplay-v1.png",
  "/ludo/ui/icons/players.png",
  "/ludo/ui/icons/ready.png",
  "/ludo/ui/icons/robot.png",
  "/ludo/ui/icons/send.png",
  "/ludo/ui/icons/settings.png",
  "/ludo/ui/lobby-logo.png",
  "/ludo/ui/top-info-panel-bg.png"
];

/** 模型、音频与 Effekseer 运行时:fetch 一遍进 HTTP 缓存,解码交给各自的运行时 */
export const LUDO_BLOBS: string[] = [
  "/ludo/audio/dice-roll.wav",
  "/ludo/audio/home-lane.wav",
  "/ludo/audio/intro-dice-fall.wav",
  "/ludo/audio/intro-dice-land-body.wav",
  "/ludo/audio/intro-dice-land-click.wav",
  "/ludo/audio/intro-dice-six.wav",
  "/ludo/audio/intro-dice-spin.wav",
  "/ludo/audio/intro-piece-sweep.wav",
  "/ludo/audio/intro-vs-crack.wav",
  "/ludo/audio/intro-vs-spark.wav",
  "/ludo/audio/intro-vs-sub.wav",
  "/ludo/audio/piece-capture.wav",
  "/ludo/audio/piece-home.wav",
  "/ludo/audio/piece-step.wav",
  "/ludo/audio/room-join.wav",
  "/ludo/audio/victory.wav",
  "/ludo/effekseer/runtime/effekseer.min.js",
  "/ludo/effekseer/runtime/effekseer.wasm",
  "/ludo/effekseer/vs/Parts/AuraTube.efkmat",
  "/ludo/effekseer/vs/Parts/AuraTubeModel.efkmodel",
  "/ludo/effekseer/vs/Parts/Impact.efkmodel",
  "/ludo/effekseer/vs/Parts/Noise_Distortion.efkmat",
  "/ludo/effekseer/vs/Parts/RadiarNoise.efkmat",
  "/ludo/effekseer/vs/Parts/Round.efkmodel",
  "/ludo/effekseer/vs/Parts/ToonBase.efkmat",
  "/ludo/effekseer/vs/Parts/ToonImpact.efkmat",
  "/ludo/effekseer/vs/Parts/ToonWater.efkmat",
  "/ludo/effekseer/vs/Parts/ToonWaterTube.efkmat",
  "/ludo/effekseer/vs/Parts/Tube.efkmodel",
  "/ludo/effekseer/vs/vs-burst-v1806.efkefc",
  "/ludo/effekseer/vs/vs-burst.efkefc",
  "/ludo/models/dice-complete-v2.glb",
  "/ludo/models/dice.glb",
  "/ludo/models/pawn.glb"
];

export const LUDO_ASSET_COUNT = 88;
